'use client';
import {useEffect,useRef,useState} from 'react';
import {WritingObject} from './WritingObject';
import './writing.css';
import './building.css';
const assets='/assets/personal/building/';
const projects={
 discova:{name:'Discova',status:'Live',role:'Builder',heading:<>A calmer way<br/>to <em>follow curiosity.</em></>,intro:'Technology makes it easy to collect more things to read. I wanted to make it easier to actually learn something.',body:'I built Discova around a small choice: pick a technology topic, discover one article, and give it your attention. The product brings discovery and reading into one focused flow.',decision:'Keep the next step small.',detail:'A topic selector leads to a single article rather than another feed. The reading view keeps the source available and gives the idea room to be understood.',screens:[['discova.png','Choose a topic','Discova’s live topic selection screen'],['discova-reading.png','Read one idea','An article opened through Discova’s live discovery flow']],url:'https://discova.dev',action:'Try Discova'},
 trustkarry:{name:'TrustKarry',status:'Closed beta',role:'Founding engineer',heading:<>A clearer way<br/>to <em>coordinate a handoff.</em></>,intro:'People already help one another carry things between Canada and Nigeria. The difficult part is keeping the arrangements clear.',body:'As founding engineer, I work on the product that connects senders and travellers through trip discovery, requests, messaging, and a shared record of the handoff.',decision:'Make the next step visible to both sides.',detail:'A route match is only the beginning. Requests, messages, and recorded milestones give the sender and traveller a shared place to follow what happens next.',screens:[['trustkarry-find-trips.png','Find a matching trip','TrustKarry trip discovery demo, published by Jatto IT Solutions'],['trustkarry-request-inbox.png','Coordinate the request','TrustKarry request inbox demo, published by Jatto IT Solutions']],url:'https://trustkarry.com',action:'Explore TrustKarry'}
};
function Screens({project}){const [selected,setSelected]=useState(0);const [zoom,setZoom]=useState(false);const dialog=useRef(null),trigger=useRef(null);const screen=project.screens[selected];useEffect(()=>{if(!zoom)return;const d=dialog.current;const focusTarget=trigger.current;d.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{d.close();document.body.style.overflow=old;focusTarget?.focus()}},[zoom]);return <div className="b-screens"><div className="b-screen-choices" role="group" aria-label={project.name+' screens'}>{project.screens.map((s,i)=><button key={s[0]} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{s[1]}</button>)}</div><button ref={trigger} className="b-screen-image" onClick={()=>setZoom(true)} aria-label={'Enlarge '+screen[1]}><img src={assets+screen[0]} alt={screen[2]} loading="lazy"/><span>View full screen ↗</span></button><p className="b-caption">{project.name==='Discova'?'Captured from the live product':'Published product demo'} · Select a screen to explore</p>{zoom&&<dialog ref={dialog} className="b-lightbox" aria-label={project.name+' '+screen[1]} onCancel={()=>setZoom(false)} onClick={e=>{if(e.target===e.currentTarget)setZoom(false)}}><button autoFocus onClick={()=>setZoom(false)}>Close ×</button><img src={assets+screen[0]} alt={screen[2]}/></dialog>}</div>}
function Project({slug,detail=false}){const p=projects[slug];return <section className="b-project b-contained" id={slug} data-build-reveal><div className="b-project-heading"><div><p className="b-meta">{p.name} · {p.status} · {p.role}</p><h2>{p.heading}</h2></div><div><p>{p.intro}</p><p>{p.body}</p><a className="p-text-link" href={detail?p.url:'/building/'+slug}>{detail?p.action:'Inside the project'} ↗</a></div></div><Screens project={p}/>{detail&&<div className="b-decision"><h2>{p.decision}</h2><p>{p.detail}</p><a className="p-text-link" href={'https://jattosolutions.com/products/'+slug}>Product information at Jatto IT Solutions ↗</a></div>}</section>}
export function BuildingPage({path}){const root=useRef(null);const slug=path.split('/')[2];const detail=projects[slug];useEffect(()=>{document.title=(detail?detail.name+' | Building':'Building')+' | Jatto Abdul';const media=matchMedia('(prefers-reduced-motion: reduce)');const animations=[];const io=new IntersectionObserver(entries=>{entries.forEach(e=>{if(!e.isIntersecting)return;io.unobserve(e.target);if(!media.matches)animations.push(e.target.animate([{opacity:.4,transform:'translateY(30px)'},{opacity:1,transform:'translateY(0)'}],{duration:850,easing:'cubic-bezier(.2,.7,.2,1)'}))})},{threshold:.1});root.current.querySelectorAll('[data-build-reveal]').forEach(el=>io.observe(el));const stop=()=>{if(media.matches)animations.forEach(a=>a.finish())};media.addEventListener('change',stop);return()=>{io.disconnect();media.removeEventListener('change',stop);animations.forEach(a=>a.cancel())}},[path,detail]);return <div className="b-page" ref={root}>{detail?<><header className="b-detail-header b-contained"><a className="p-text-link" href="/building">← All my work</a><h1>{detail.name}</h1></header><Project slug={slug} detail/></>:<>
<section className="b-arrival b-contained"><div><h1>Ideas become<br/>useful when<br/>you <em>build them.</em></h1><p>I’m an engineer and entrepreneur turning curiosity into software. Sometimes I start with a problem of my own. Sometimes I join a team working through something bigger.</p><div className="b-actions"><a className="p-button" href="#discova">Explore the work ↗</a><a className="p-text-link" href="#build-together">Build with me ↗</a></div></div><WritingObject kind="assembly"/></section>
<Project slug="discova"/><Project slug="trustkarry"/>
<section className="b-teams b-contained" data-build-reveal><div className="b-section-heading"><h2>Built with teams.<br/><em>Used by people.</em></h2><p>Some of my most meaningful work has happened alongside other people, improving the systems they rely on every day.</p></div>{[{name:'Minerva',role:'Most recent full-time engagement · Senior Engineer',url:'https://gominerva.com',title:'Making screening workflows more useful.',copy:'I worked across backend, search, reporting, and platform workflows for AML screening, including sanctions, PEP, adverse media, and ongoing monitoring.'},{name:'Fera',role:'Engineer → Lead · Now consulting',url:'https://fera.ai',title:'Software behind the merchant experience.',copy:'I built and led work across reviews, Q&A, messaging, verification, widgets, dashboards, and merchant integrations in a multi-platform commerce product suite. I continue to consult with the team.'},{name:'IrisNova (Dirty Lemon)',role:'Software Engineer · Through Andela',title:'My first experience building with a global team.',copy:'Through Andela, I joined IrisNova, the company behind Dirty Lemon, and worked with Greg Leuch. It was my first international client engagement and an important chapter in learning to build software with a globally distributed team.'},{name:'Heroshe',role:'Engineer',title:'Bringing operations into clearer software.',copy:'I helped modernize logistics workflows, moving from third-party operations tooling toward custom software for shipments, customers, and internal teams.'}].map(p=><article id={p.name.toLowerCase().replace(/[^a-z]+/g,'-')} key={p.name}><div><h3>{p.url?<a href={p.url}>{p.name} ↗</a>:p.name}</h3><p className="b-meta">{p.role}</p></div><div><h3>{p.title}</h3><p>{p.copy}</p></div></article>)}<a className="p-text-link" href="/about">The journey behind the work ↗</a></section>
<section className="b-studio b-contained" data-build-reveal><div className="b-section-heading"><h2>Also<br/><em>taking shape.</em></h2><p>I’m building a family of focused products through Jatto IT Solutions. Each starts with a particular job that software could make easier.</p></div><div className="b-studio-grid">{[{name:'Pinnr',slug:'pinnr',status:'Awaiting Shopify approval',copy:'Connecting Shopify product information to Pinterest pin creation, scheduling, and publishing.'},{name:'RuleNorth',slug:'rulenorth',status:'In development',copy:'A Shopify-first workflow for screening order names and destinations, with evidence and review decisions kept together.'}].map(p=><article key={p.slug}><a className="b-studio-image" href={'https://jattosolutions.com/products/'+p.slug}><img src={assets+p.slug+'.png'} alt={p.name+' public product website'} loading="lazy"/></a><p className="b-meta">{p.status}</p><h3>{p.name}</h3><p>{p.copy}</p><a className="p-text-link" href={'https://jattosolutions.com/products/'+p.slug}>Explore {p.name} at the studio ↗</a></article>)}</div></section>
<section id="experiments" className="b-experiments b-contained" data-build-reveal><h2>Still curious.<br/><em>Still building.</em></h2><div><p className="b-meta">InferGo · Public alpha</p><h3>What if inference could live<br/>inside the Go service?</h3><p>InferGo explores running supported models in Go without Python in production. It’s part of my ongoing interest in developer tools and the decisions that make software easier to operate.</p><a className="p-button" href="https://github.com/pergamon-labs/infergo">Explore InferGo on GitHub ↗</a><a className="p-text-link" href="/writing/audience-of-one">Read: Writing for the engineer who comes next ↗</a></div></section>
</>}<section id="build-together" className="b-invite b-contained" data-build-reveal><h2>What are you trying<br/>to <em>make possible?</em></h2><p>An engineering role. A product that needs thoughtful execution. A difficult problem worth understanding. I’d like to hear what you’re working on.</p><a className="p-button" href="mailto:me@jattoabdul.com?subject=Let%E2%80%99s%20build%20something">Start a conversation ↗</a><a className="p-text-link" href="https://jattosolutions.com">For product and studio enquiries, visit Jatto IT Solutions ↗</a></section></div>}
