import {Testimonials,Footer,ContactButton} from './SiteShell';
function Arrow(){return <span aria-hidden="true" className="p-arrow">↗</span>}
function ChapterLabel({children}){return <p className="p-eyebrow">{children}</p>}
export default function HomeStory(){return <>
      <section className="p-chapter p-arrival" id="arrival" data-chapter="0" aria-labelledby="arrival-heading"><div className="p-stage"><div className="p-copy"><h1 id="arrival-heading">I am<br/>Jatto<br/>Abdul.</h1><div className="p-arrival-body"><p className="p-eyebrow">Engineer. Entrepreneur. Mentor. Author.</p><p>I build software, share ideas, and mentor young people navigating career, character, and faith, so they can <em>grow without losing themselves</em>.</p><div className="p-hero-actions"><a className="p-button" href="/building">Explore my work <Arrow/></a><a className="p-button p-button-secondary" href="/writing">Read my notes <Arrow/></a></div></div></div><span className="p-scroll-note">Scroll to explore</span></div></section>
      <section className="p-chapter p-person" id="person" data-chapter="1" aria-labelledby="person-heading"><div className="p-stage"><div className="p-copy"><h2 id="person-heading">I’m growing,<br/><em>too.</em></h2><p>In what I build. In how I lead. In what I believe. I’m learning how to pursue my ambitions without leaving my foundations behind.</p><p className="p-secondary">When a lesson helps me see more clearly, I share it through writing, speaking, and the work I put into the world. My hope is that it helps someone coming after me find their own next step.</p><a className="p-text-link" href="/about">A little more about me <Arrow/></a></div></div></section>
      <section className="p-chapter p-scatter" id="sharing" data-chapter="2" aria-labelledby="sharing-heading"><div className="p-stage"><div className="p-copy"><h2 id="sharing-heading">Still learning.<br/>Sharing as I go.</h2><a className="p-button" href="/speaking">Explore my talks <Arrow/></a></div></div></section>
      <section className="p-chapter p-mission-section" id="mission" data-chapter="3" aria-label="My mission"><div className="p-stage"><div className="p-copy p-mission"><p>I believe young people can build meaningful careers, companies, and influence <em>without trading away who they are.</em></p><p>You can hold your faith and ambition in the same hands. Start before you feel ready. Stay close to God. Stay true to yourself.</p><p>This is the life I’m building in public, and you’re welcome to grow with me.</p></div></div></section>
      <section className="p-chapter p-ideas" id="ideas" data-chapter="4" aria-labelledby="ideas-heading"><div className="p-stage"><div className="p-copy"><h2 id="ideas-heading">Ideas take shape<br/>in the work.</h2><p>Sometimes that means building software. Sometimes it means putting a difficult lesson into words.</p><p className="p-secondary">Here are a few things I’ve made and shared, and what I hope they make possible for others.</p></div></div></section>
      <section className="p-chapter p-project" id="selected-work" data-chapter="5" aria-labelledby="project-heading"><div className="p-stage"><div className="p-copy"><ChapterLabel>Something I’m building</ChapterLabel><h2 id="project-heading">Less searching.<br/>More learning.</h2><p className="p-feature-name">Discova</p><p>Useful engineering ideas are scattered across feeds, articles, and saved links. I built Discova to bring them into a calmer reading and discovery flow.</p><p className="p-secondary">A product for turning scattered links into something you can learn from.</p><a className="p-button" href="/building/discova">Explore the project <Arrow/></a><aside className="p-supporting-project"><p className="p-eyebrow">Also building</p><h3>TrustKarry</h3><p>A marketplace connecting senders with trusted travellers. My role: founding engineer.</p><a className="p-text-link" href="/building/trustkarry">Explore TrustKarry <Arrow/></a></aside></div></div></section>
      <section className="p-chapter p-essay" id="selected-writing" data-chapter="6" aria-labelledby="essay-heading"><div className="p-stage"><div className="p-copy"><ChapterLabel>Something I’ve learned</ChapterLabel><h2 id="essay-heading">Put it into words.<br/>See it more clearly.</h2><p>Writing makes me confront what I understand, and what I only think I do. Sharing it gives someone else a place to begin.</p><p className="p-feature-name">Why I write as an engineer<br/>(and you probably should too)</p><a className="p-button" href="/writing/writing-as-engineer">Read the story <Arrow/></a></div></div></section>
      <section className="p-chapter p-speaking-feature" id="selected-speaking" data-chapter="7" aria-labelledby="speaking-heading"><div className="p-stage"><div className="p-copy"><h2 id="speaking-heading">Some conversations<br/>need a voice.</h2><p>Writing helps me find the words. Speaking lets me bring them into a conversation, through talks, videos, and the questions we explore together.</p><article className="p-video-feature"><a className="p-video-poster" href="https://youtu.be/pu-IHuL--hg" aria-label="Watch Why the Best Engineers Get Overlooked on YouTube"><img src="/assets/personal/engineers-overlooked.jpg" alt="" loading="lazy"/><span aria-hidden="true">▶</span></a><h3>Why the Best Engineers Get Overlooked<br/>(and How to Fix It)</h3><p>A conversation about making your engineering work more visible.</p><a className="p-button" href="https://youtu.be/pu-IHuL--hg">Watch the conversation <Arrow/></a><a className="p-text-link" href="https://www.youtube.com/@jatto_abdul">More on YouTube <Arrow/></a></article></div></div></section>
      <section className="p-chapter p-mentoring-feature" id="mentoring" data-chapter="8" aria-labelledby="mentoring-heading"><div className="p-stage"><div className="p-copy"><h2 id="mentoring-heading">Find your footing.<br/><em>Take your next step.</em></h2><p>I share what I’m learning for young people finding their way through career, character, and faith.</p><p className="p-secondary">Sometimes a useful idea is enough to get started. Sometimes you need a conversation with someone who will listen.</p><p className="p-secondary">Through videos, social posts, and conversations, I want to help you find a next step that feels true to who you are.</p><div className="p-mentoring-actions"><ContactButton>Start a conversation <Arrow/></ContactButton><a className="p-text-link" href="https://www.instagram.com/jatto_abdul/">Follow along on Instagram <Arrow/></a></div></div></div></section>
      <Testimonials/>
      <section className="p-chapter p-rooted" id="foundation" data-chapter="10" aria-labelledby="rooted-heading"><div className="p-stage"><div className="p-copy"><h2 id="rooted-heading">Keep becoming.<br/><em>Stay rooted.</em></h2></div></div></section>
      <section className="p-chapter p-finale" id="invitation" data-chapter="11" aria-labelledby="invitation-heading"><div className="p-stage"><div className="p-copy"><h2 id="invitation-heading">What are you<br/>working toward?</h2><p>A career move. An idea you want to build. A question about faith, ambition, or what comes next.</p><p className="p-secondary">I’d like to hear where you are and what you’re figuring out.</p><ContactButton>Let’s talk <Arrow/></ContactButton><a className="p-text-link" href="https://www.youtube.com/@jatto_abdul">Keep growing with me on YouTube <Arrow/></a></div><Footer/></div></section>
    </>}
