'use client';
import {useEffect,useRef,useState} from 'react';
import {SpeakingParticles} from './SpeakingParticles';
import './speaking.css';
const assets='/assets/personal/speaking/';
const videos=[
 {id:'3laKATXgM08',title:'If Your Platform Has No Golden Path, AI Will Multiply the Chaos',date:'2026-08-19',image:'golden-path',format:'Videos & reflections'},
 {id:'pu-IHuL--hg',title:'Why the Best Engineers Get Overlooked (and How to Fix It)',date:'2026-08-05',image:'overlooked',format:'Videos & reflections'},
 {id:'1hSbkm97WfU',title:'Flowers For My Mother While She Can Hear',date:'2026-04-07',image:'mother',format:'Spoken word'},
 {id:'remz7G5ZVjQ',title:'Welcome to our live show!',date:'2026-03-29',image:'live',format:'Conversations'},
 {id:'DWmDZ9pUjwk',title:'From Idea to Live MVP: Building Discova with AI Agents',date:'2026-03-21',image:'discova',format:'Videos & reflections'},
];
export function Player({video,close}){const ref=useRef(null);useEffect(()=>{const d=ref.current;const old=document.body.style.overflow;document.body.style.overflow='hidden';d.showModal();return()=>{d.close();document.body.style.overflow=old}},[]);return <dialog ref={ref} className="s-player" aria-labelledby="s-player-title" onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close()}}><div><button autoFocus className="s-player-close" onClick={close}>Close ×</button><h2 id="s-player-title">{video.title}</h2><iframe src={'https://www.youtube-nocookie.com/embed/'+video.id+'?autoplay=1&rel=0'} title={video.title} allow="autoplay; encrypted-media; picture-in-picture; fullscreen"/><a href={'https://www.youtube.com/watch?v='+video.id} target="_blank" rel="noreferrer">Watch on YouTube ↗</a></div></dialog>}
function Poster({video,onPlay,large=false}){return <button className={'s-poster'+(large?' s-poster-large':'')} onClick={()=>onPlay(video)} aria-label={'Watch '+video.title}><img src={assets+video.image+'.jpg'} alt="" loading="lazy"/><span className="s-play"><span aria-hidden="true">▶</span> Watch</span></button>}
export function Ambient({suspended}){const ref=useRef(null);const [stopped,setStopped]=useState(null),[playing,setPlaying]=useState(false);useEffect(()=>{const v=ref.current;const reduce=matchMedia('(prefers-reduced-motion: reduce)');let visible=true;const sync=()=>{if(!visible||document.hidden||(reduce.matches&&stopped!==false)||stopped||suspended)v.pause();else v.play().catch(()=>setPlaying(false))};const io=new IntersectionObserver(([e])=>{visible=e.isIntersecting;sync()});io.observe(v);reduce.addEventListener('change',sync);document.addEventListener('visibilitychange',sync);sync();return()=>{io.disconnect();reduce.removeEventListener('change',sync);document.removeEventListener('visibilitychange',sync);v.pause()}},[stopped,suspended]);return <div className="s-ambient"><video ref={ref} muted loop playsInline preload="metadata" poster={assets+'arrival-poster.jpg'} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} aria-label="Silent footage of Jatto speaking at his desk"><source src={assets+'arrival-muted.mp4'} type="video/mp4"/></video><button onClick={()=>setStopped(playing?true:false)} aria-pressed={!!stopped}>{playing?'Pause preview':'Play preview'} <span aria-hidden="true">{playing?'Ⅱ':'▶'}</span></button></div>}
const invite='mailto:me@jattoabdul.com?subject=Speaking%20invitation&body=Hello%20Jatto%2C%0A%0AAudience%3A%20%0ATopic%3A%20%0ADate%3A%20%0ALocation%20or%20online%3A%20%0AFormat%3A%20';
export function SpeakingPage({archiveOnly=false}){const [selected,setSelected]=useState(null),[filter,setFilter]=useState('All'),[query,setQuery]=useState('');const pageRef=useRef(null);useEffect(()=>{const reduce=matchMedia('(prefers-reduced-motion: reduce)');const animations=[];const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;observer.unobserve(entry.target);if(!reduce.matches)animations.push(entry.target.animate([{opacity:.35,transform:'translateY(30px)'},{opacity:1,transform:'translateY(0)'}],{duration:850,easing:'cubic-bezier(.2,.7,.2,1)'}))}},{threshold:.12});pageRef.current.querySelectorAll('.s-feature-copy,.s-feature>.s-poster,.s-poetry,.s-topics,.s-invite').forEach(el=>observer.observe(el));const stop=()=>{if(reduce.matches)animations.forEach(a=>a.finish())};reduce.addEventListener('change',stop);return()=>{observer.disconnect();animations.forEach(a=>a.cancel());reduce.removeEventListener('change',stop)}},[archiveOnly]);const focus=useRef(null);const play=video=>{focus.current=document.activeElement;setSelected(video)};const close=()=>{setSelected(null);requestAnimationFrame(()=>focus.current?.focus())};useEffect(()=>{document.title=(archiveOnly?'Videos':'Speaking')+' | Jatto Abdul'},[archiveOnly]);const shown=videos.filter(v=>(filter==='All'||v.format===filter)&&v.title.toLowerCase().includes(query.toLowerCase()));return <div ref={pageRef} className="s-page">
{!archiveOnly&&<><SpeakingParticles paused={!!selected}/><section className="s-arrival"><Ambient suspended={!!selected}/><div className="s-introduction"><h1>Some ideas<br/>come alive in<br/><em>conversation.</em></h1><p>I share what I’m learning about work, faith, and finding your way, through videos, talks, and honest conversations.</p><div className="s-actions"><button className="p-button" onClick={()=>play(videos[1])}>Watch a conversation ▶</button><a className="p-text-link" href="#invite">Invite me to speak ↗</a></div></div></section>
<section id="start-watching" className="s-feature s-contained"><div className="s-feature-copy"><h2>A place<br/>to <em>begin.</em></h2><div><p>Making your work visible starts with helping people understand its value.</p><h3>{videos[1].title}</h3></div></div><Poster video={videos[1]} onPlay={play} large/></section>
<section className="s-poetry s-contained"><div><h2>Some words<br/>ask to be<br/><em>spoken.</em></h2><p>A tribute to my mother, and to the love, discipline, and faith that helped shape the person I’m becoming.</p><p className="s-title">{videos[2].title}</p><button className="p-text-link" onClick={()=>play(videos[2])}>Watch the spoken word ↗</button><a className="p-text-link s-related" href="/writing#poetry">The written side ↗</a></div><Poster video={videos[2]} onPlay={play}/></section></>}
<section id="recordings" className="s-library s-contained">{archiveOnly?<><a className="p-text-link" href="/speaking">← Speaking</a><h1>Keep the<br/><em>conversation going.</em></h1></>:<h2>Keep the<br/><em>conversation going.</em></h2>}<p>Ideas, reflections, and things I’m learning in public. Find something that speaks to where you are.</p><div className="s-library-controls"><label>Find a recording<input type="search" placeholder="Search recordings" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Format<select value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Videos & reflections','Conversations','Spoken word'].map(f=><option key={f}>{f}</option>)}</select></label></div><p className="s-count" role="status">{shown.length} {shown.length===1?'recording':'recordings'}</p><div className="s-recordings">{shown.map(v=><article key={v.id}><Poster video={v} onPlay={play}/><p className="s-meta">{v.format} · <time dateTime={v.date}>{new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(v.date+'T12:00:00Z'))}</time></p><h3><button onClick={()=>play(v)}>{v.title}</button></h3></article>)}</div>{!shown.length&&<p>No recordings match. Try another search or choose All.</p>}<a href="https://www.youtube.com/@jatto_abdul" className="p-text-link">Follow along on YouTube ↗</a></section>
{!archiveOnly&&<><section className="s-topics s-contained"><div className="s-topics-photo"><img src={assets+'arrival-poster.jpg'} alt="Jatto speaking into a microphone at his desk" loading="lazy"/></div><div><h2>A conversation<br/>for your<br/><em>community.</em></h2><article><h3>Career and visibility</h3><p>For people finding their footing: communicating useful work, developing judgment, and taking the next step.</p></article><article><h3>Faith, ambition, and character</h3><p>For young people carrying big hopes: pursuing growth while staying close to the values that guide you.</p></article><article><h3>Building with judgment</h3><p>For engineers and builders: turning problems into products and working with AI responsibly.</p></article><p className="s-formats">Talks · Panels · Community conversations · Podcast appearances</p></div></section><section id="invite" className="s-invite s-contained"><h2>What would help<br/>your audience<br/><em>move forward?</em></h2><p>Tell me who you’re bringing together, what they’re navigating, and the conversation you hope to have.</p><a className="p-button" href={invite}>Invite me to speak ↗</a><a className="p-text-link" href="/downloads/jatto-abdul-press-kit-v2.3.pdf">Download the press kit ↓</a></section></>}{selected&&<Player video={selected} close={close}/>}</div>}
