'use client';
import {useEffect,useRef} from 'react';
import * as THREE from 'three';
export function SpeakingParticles({paused}){
 const canvas=useRef(null),pause=useRef(paused),resumeRef=useRef(null);pause.current=paused;
 useEffect(()=>{resumeRef.current?.()},[paused]);
 useEffect(()=>{const el=canvas.current;let renderer;try{renderer=new THREE.WebGLRenderer({canvas:el,alpha:true,antialias:true})}catch{return}renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,50);camera.position.z=7;
 const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute([-.5,-.4,0,.5,-.4,0,0,.6,0],3));const mat=new THREE.MeshBasicMaterial({side:THREE.DoubleSide,transparent:true});const count=1600,mesh=new THREE.InstancedMesh(geo,mat,count);scene.add(mesh);const points=[],dummy=new THREE.Object3D();let seed=431;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);const colours=['#efc9a3','#792a3d','#7392b8','#f4eee6'];for(let i=0;i<count;i++){let x,y,z;const a=random()*Math.PI*2;if(i<1100){y=(random()-.5)*1.35+.5;const r=.48*Math.sqrt(Math.max(.15,1-Math.pow((y-.5)/.9,4)));x=Math.cos(a)*r;z=Math.sin(a)*r}else if(i<1450){y=-.15-random()*1.25;x=Math.cos(a)*.13;z=Math.sin(a)*.13}else{const r=Math.sqrt(random())*.65;x=Math.cos(a)*r;y=-1.45;z=Math.sin(a)*r}points.push({x,y,z,noise:random()});mesh.setColorAt(i,new THREE.Color(colours[i%4]))}
 const reduce=matchMedia('(prefers-reduced-motion: reduce)');let raf=0,dead=false,visible=true,progress=0;const start=performance.now();
 function size(){renderer.setSize(el.clientWidth,el.clientHeight,false);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix()}
 function draw(){raf=0;if(dead||!visible||document.hidden||pause.current)return;if(!reduce.matches)raf=requestAnimationFrame(draw);const p=Math.min(2.3,scrollY/innerHeight);progress+=(p-progress)*.08;const morph=reduce.matches?0:Math.max(0,Math.min(1,(progress-.2)/.75));const opacity=Math.max(0,1-Math.max(0,progress-1)*1.2)*.55;el.style.opacity=opacity;if(!opacity)return;const scatter=reduce.matches?0:Math.max(0,progress-1);const entrance=reduce.matches?0:1-Math.min(1,(performance.now()-start)/1300);points.forEach((v,i)=>{const tx=(i/count-.5)*4.8;const ty=Math.sin(i/count*Math.PI*18)*(.15+.55*Math.pow(Math.sin(i/count*Math.PI),2));dummy.position.set(v.x*(1-morph)+tx*morph+Math.sin(i)*(entrance+scatter*3),v.y*(1-morph)+ty*morph+Math.cos(i*2)*scatter*3,v.z*(1-morph)+v.noise*.2*morph);dummy.rotation.set(i*.4,i*.3,i*.9);dummy.scale.setScalar(.027+v.noise*.028);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix)});mesh.instanceMatrix.needsUpdate=true;mesh.rotation.y=-.2;renderer.render(scene,camera)}
 const resume=()=>{cancelAnimationFrame(raf);raf=0;draw()};resumeRef.current=resume;
 const io=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;resume()});io.observe(el);
 const ro=new ResizeObserver(()=>{size();resume()});ro.observe(el);document.addEventListener('visibilitychange',resume);reduce.addEventListener('change',resume);size();draw();const lost=e=>{e.preventDefault();dead=true;el.style.display='none';cancelAnimationFrame(raf)};el.addEventListener('webglcontextlost',lost);return()=>{dead=true;cancelAnimationFrame(raf);ro.disconnect();io.disconnect();document.removeEventListener('visibilitychange',resume);reduce.removeEventListener('change',resume);resumeRef.current=null;el.removeEventListener('webglcontextlost',lost);geo.dispose();mat.dispose();renderer.dispose()};
 },[]);return <canvas ref={canvas} className="s-particles" aria-hidden="true"/>;
}
