'use client';
import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import data from './content/writing';
const LazyWritingObject=lazy(()=>import('./WritingObject').then(module=>({default:module.WritingObject})));
function WritingObject({kind='particles'}){return <Suspense fallback={<div className={'w-object w-object-'+kind} aria-hidden="true"/>}><LazyWritingObject kind={kind}/></Suspense>}
import './writing.css';
const date=value=>new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(value+'T12:00:00Z'));
const local=data.essays.map(e=>({...e,format:'Essay',url:'/writing/'+e.slug}));
const all=[...local,...data.medium].sort((a,b)=>b.date.localeCompare(a.date));
const note=slug=>data.notes.find(n=>n.slug===slug);
function Meta({item}){return <p className="w-meta">{item.format||'Note'} <span>·</span> <time dateTime={item.date}>{date(item.date)}</time>{item.kind==='medium'&&<> <span>·</span> Medium ↗</>}</p>}
function useReveal(ref){useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');if(q.matches)return;const animations=[];const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){animations.push(e.target.animate([{opacity:.25,transform:'translateY(22px)'},{opacity:1,transform:'translateY(0)'}],{duration:800,easing:'cubic-bezier(.2,.7,.2,1)'}));io.unobserve(e.target)}}),{threshold:.1});ref.current.querySelectorAll('[data-reveal]').forEach(el=>io.observe(el));const stop=()=>{if(q.matches){io.disconnect();animations.forEach(a=>a.cancel())}};q.addEventListener('change',stop);return()=>{q.removeEventListener('change',stop);io.disconnect();animations.forEach(a=>a.cancel())}},[ref])}
function BookFeature({standalone=false}){const Heading=standalone?'h1':'h2';return <section className="w-book-section" id="book" aria-labelledby="book-title"><div className="w-book-art"><WritingObject kind="cover"/></div><div data-reveal><p className="w-status">Book in progress · Coming soon</p><Heading id="book-title">Present Without<br/><em>Performing.</em></Heading><p className="w-working">Working title</p><p className="w-book-subtitle">Finding your voice and sharing your work without losing yourself.</p><p>I’m working on a book about showing up with purpose: finding your voice, sharing what you know, and pursuing your ambitions while staying close to your faith and values.</p><a className="p-button" href="/books/present-without-performing">About the book <span aria-hidden="true">↗</span></a></div></section>}
function Archive({notes=false}){
 const params=new URLSearchParams('');const [query,setQuery]=useState(params.get('q')||params.get('tag')||'');const [filter,setFilter]=useState(params.get('format')||'All');
 useEffect(()=>{const p=new URLSearchParams(location.search);setQuery(p.get('q')||p.get('tag')||'');setFilter(p.get('format')||'All')},[]);
 const items=notes?data.notes.map(n=>({...n,format:'Note',url:'/notes/'+n.slug})):all;
 const filters=notes?['All',...new Set(data.notes.flatMap(n=>n.tags))]:['All','Essay','Poetry','Reflection'];
 const shown=items.filter(p=>(filter==='All'||(notes?p.tags.includes(filter):p.format===filter))&&`${p.title} ${p.excerpt||''} ${(p.tags||[]).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 function update(value,key){const url=new URL(location.href);if(key==='q')url.searchParams.delete('tag');if(value&&value!=='All')url.searchParams.set(key,value);else url.searchParams.delete(key);history.replaceState(null,'',url);}
 return <div className="w-archive"><div className="w-archive-tools"><label>Find something to read<input type="search" value={query} placeholder="Search titles and topics" onChange={e=>{setQuery(e.target.value);update(e.target.value,'q')}}/></label><label>{notes?'Topic':'Format'}<select value={filter} onChange={e=>{setFilter(e.target.value);update(e.target.value,'format')}}>{filters.map(f=><option key={f}>{f}</option>)}</select></label></div><p className="w-count" role="status">{shown.length} {shown.length===1?'piece':'pieces'}</p><div className="w-archive-list">{shown.map((p,i)=><article key={p.url}>{notes&&(i===0||shown[i-1].date.slice(0,7)!==p.date.slice(0,7))&&<h3 className="w-month">{new Intl.DateTimeFormat('en',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(p.date+'T12:00:00Z'))}</h3>}<Meta item={p}/><h3><a href={p.url}>{p.title}<span aria-hidden="true">↗</span></a></h3>{p.excerpt&&<p>{p.excerpt}</p>}</article>)}</div>{!shown.length&&<p>No pieces match that search. Try another word or choose All.</p>}</div>
}
export function WritingPage(){const root=useRef(null);useReveal(root);useEffect(()=>{document.title='Writing | Jatto Abdul'},[]);const first=local.find(p=>p.slug==='writing-as-engineer');return <div className="w-page" ref={root}>
<section className="w-arrival"><div><h1>A few things<br/>worth putting<br/>into <em>words.</em></h1><p>I write to understand what I’m learning and to pass on what might help. Essays on work and life, poems, and notes from the middle of figuring things out.</p><a className="p-text-link" href="#collection">Browse all writing ↗</a></div><WritingObject/></section>
<nav className="w-sections" aria-label="Writing sections"><a href="#essays">Essays</a><a href="#poetry">Poetry</a><a href="#notes">Notes &amp; commentaries</a><a href="#book">Book in progress</a></nav>
<section id="essays" className="w-selected"><h2 data-reveal>A place to begin.</h2><div className="w-selected-grid"><article className="w-lead" data-reveal><a className="w-image-link" href={first.url} tabIndex={-1} aria-hidden="true"><img src="/assets/personal/about-first-pages.webp" alt="" loading="lazy"/></a><Meta item={first}/><h3><a href={first.url}>{first.title}</a></h3><p>{first.excerpt}</p><a className="p-text-link" href={first.url}>Read the essay ↗</a></article><div className="w-supporting">{[ {...note('rest-is-not-a-reward-for-certainty'),url:'/notes/rest-is-not-a-reward-for-certainty',excerpt:'On making room for recovery when the next chapter is still uncertain.'},local.find(p=>p.slug==='staff-judgment')].map(p=><article key={p.url} data-reveal><Meta item={p}/><h3><a href={p.url}>{p.title}</a></h3><p>{p.excerpt}</p><a href={p.url} className="p-text-link">Read {p.format?'the essay':'the note'} ↗</a></article>)}</div></div></section>
<section id="poetry" className="w-poetry" data-reveal><div><h2>Some things<br/>arrive as <em>poems.</em></h2><p>Have You Pictured Your Life?</p><span className="w-meta">Poetry · 16 June 2019</span></div><div><blockquote>I realize my picture is me.<br/>This frame is me in my world’s<br/>highest definition-HD.</blockquote><p className="w-poem-description">An early poem about uncertainty, self-recognition, and the picture we make of a life.</p><a className="p-text-link" href="https://medium.com/@jattoabdul/have-you-pictured-your-life-8987ba19890f">Read the poem on Medium ↗</a></div></section>
<section id="notes" className="w-notes-feature"><h2 data-reveal>Still thinking<br/><em>it through.</em></h2><p>Short observations on what I’m building, learning, reading, and trying to understand.</p><div className="w-note-preview">{['skill-you-stop-practicing','shipping-and-distribution-are-different-jobs','last-handoff-still-counts'].map(slug=>{const p=note(slug);return <article key={slug} data-reveal><Meta item={p}/><h3><a href={'/notes/'+slug}>{p.title} ↗</a></h3></article>})}</div><a href="/notes" className="p-button">Explore the notes ↗</a></section>
<BookFeature/>
<section id="collection" className="w-collection"><h2>The writing,<br/><em>so far.</em></h2><p>Essays, poems, and earlier pages. Some live here; others open on Medium.</p><Archive/></section>
<section className="w-close"><h2>Some ideas need<br/>a <em>conversation.</em></h2><p>The spoken side of what I share, through videos, talks, and conversations.</p><a className="p-text-link" href="/speaking">Explore speaking ↗</a></section>
</div>}
export function NotesPage(){useEffect(()=>{document.title='Notes | Jatto Abdul'},[]);return <div className="w-page w-notes-page"><a href="/writing#notes" className="p-text-link">← Writing</a><h1>Notes in<br/><em>progress.</em></h1><p className="w-intro">Short observations, reflections, and things I’m still working through. An ongoing record of work and life.</p><Archive notes/></div>}
export function BookPage(){useEffect(()=>{document.title='Present Without Performing | Jatto Abdul'},[]);return <div className="w-page w-book-page"><a href="/writing#book" className="p-text-link">← Writing</a><BookFeature standalone/><section className="w-book-details"><h2>A voice you can<br/><em>recognise as yours.</em></h2><p>How do you begin sharing before you feel ready? What is worth saying? How do you pursue your ambitions while staying close to your faith and values?</p><p>These are some of the questions I’m exploring in this book. It is still taking shape, and the title is a working one.</p><p>In the meantime, the essays and notes are a place to follow what I’m learning.</p><a className="p-button" href="/writing#collection">Read along ↗</a></section></div>}
